name: shelf_modular
description: An Dependency Injection plugin to Shelf
version: 1.0.0
homepage: https://github.com/RafaelSilvaPereira/shelf_modular

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  shelf_router: ^1.1.1
